// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForEnqueueContentItems implements pgx.CopyFromSource.
type iteratorForEnqueueContentItems struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForEnqueueContentItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForEnqueueContentItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForEnqueueContentItems) Err() error {
	return nil
}

func (q *Queries) EnqueueContentItems(ctx context.Context, payload []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"content_queue"}, []string{"payload"}, &iteratorForEnqueueContentItems{rows: payload})
}

// iteratorForEnqueueProfileItems implements pgx.CopyFromSource.
type iteratorForEnqueueProfileItems struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForEnqueueProfileItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForEnqueueProfileItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForEnqueueProfileItems) Err() error {
	return nil
}

func (q *Queries) EnqueueProfileItems(ctx context.Context, payload []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"profile_queue"}, []string{"payload"}, &iteratorForEnqueueProfileItems{rows: payload})
}

// iteratorForEnqueueUserItems implements pgx.CopyFromSource.
type iteratorForEnqueueUserItems struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForEnqueueUserItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForEnqueueUserItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForEnqueueUserItems) Err() error {
	return nil
}

func (q *Queries) EnqueueUserItems(ctx context.Context, payload []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"user_queue"}, []string{"payload"}, &iteratorForEnqueueUserItems{rows: payload})
}
