// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BlogPost struct {
	BlogPlatform string
	PostUrl      string
	Path         string
	PublishedAt  pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type BlogUser struct {
	BlogPlatform   string
	UserID         string
	LastEnqueuedAt pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
}

type ContentQueue struct {
	ID          int32
	Payload     string
	EnqueuedAt  pgtype.Timestamp
	LockedUntil pgtype.Timestamp
	Attempts    int32
	Status      string
}

type Link struct {
	Url            string
	LastEnqueuedAt pgtype.Timestamp
	CreatedAt      pgtype.Timestamp
}

type ProfileQueue struct {
	ID          int32
	Payload     string
	EnqueuedAt  pgtype.Timestamp
	LockedUntil pgtype.Timestamp
	Attempts    int32
	Status      string
}

type UserQueue struct {
	ID          int32
	Payload     string
	EnqueuedAt  pgtype.Timestamp
	LockedUntil pgtype.Timestamp
	Attempts    int32
	Status      string
}
